# Generated by Django 4.2.5 on 2023-10-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0003_remove_customers_date_customers_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
